version: "3"

services:
  app:
    build: .
    command: uvicorn --host 0.0.0.0 --port 8000 --reload security_study:app
    environment:
      SECRET_KEY: my-secret-key
    ports:
      - "8000:8000"
    volumes:
      - .:/home/appuser/app
