[workspace]
resolver = "2"

members = [
    "empty_window",
    "move_animated_character",
    "move_sprite",
    "move_square",
    "simple_grid_move",
    "simple_tilemap",
]

[profile.dev.package."*"]
opt-level = 3
