SCALE_FACTOR = 4
WINDOW_TITLE = "Tic-Tac-Toe"
WINDOW_SIZE = (128 * SCALE_FACTOR, 128 * SCALE_FACTOR)

BOARD_SIZE = WINDOW_SIZE
TILE_SIZE = 32 * SCALE_FACTOR
HALF_TILE_SIZE = int(TILE_SIZE / 2)
QUARTER_TILE_SIZE = int(HALF_TILE_SIZE / 2)
FPS = 30
