version: "3.9"

services:
  web:
    build: .
    command: [
      "dockerize",
      "-wait",
      "tcp://db:5432",
      "--",
      "gunicorn", "--reload", "--bind", "0.0.0.0:8000", "config.wsgi"
    ]
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
