[package]
name = "tokio-playground"
version = "0.1.0"
edition = "2024"
default-run = "tokio-playground"

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
