default: format lint-fix test

@build:
    cargo build

@run binary="":
    [[ -z "{{binary}}" ]] \
        && cargo run \
        || cargo run --bin {{binary}}

@watch:
    bacon

@format:
    cargo fmt

@lint:
    cargo clippy

@lint-fix:
    cargo clippy --fix --allow-dirty

@ci:
    cargo fmt --check
    cargo clippy

@test:
    cargo test

@clean:
    cargo clean
