setup type="Debug":
    cmake \
        -B build \
        -S . \
        -G Ninja \
        -DCMAKE_BUILD_TYPE={{type}} \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DSDL2IMAGE_PNG=ON \
        -DSDL2MIXER_WAVE=ON \
        -DSDL2MIXER_VORBIS=STB \
        -DSDL2IMAGE_AVIF=OFF \
        -DSDL2IMAGE_BMP=OFF \
        -DSDL2IMAGE_GIF=OFF \
        -DSDL2IMAGE_JPG=OFF \
        -DSDL2IMAGE_JXL=OFF \
        -DSDL2IMAGE_LBM=OFF \
        -DSDL2IMAGE_PCX=OFF \
        -DSDL2IMAGE_PNM=OFF \
        -DSDL2IMAGE_QOI=OFF \
        -DSDL2IMAGE_SVG=OFF \
        -DSDL2IMAGE_TGA=OFF \
        -DSDL2IMAGE_TIF=OFF \
        -DSDL2IMAGE_WEBP=OFF \
        -DSDL2IMAGE_XCF=OFF \
        -DSDL2IMAGE_XPM=OFF \
        -DSDL2IMAGE_XV=OFF \
        -DSDL2MIXER_FLAC=OFF \
        -DSDL2MIXER_GME=OFF \
        -DSDL2MIXER_MIDI=OFF \
        -DSDL2MIXER_MOD=OFF \
        -DSDL2MIXER_MP3=OFF \
        -DSDL2MIXER_OPUS=OFF \
        -DSDL2MIXER_WAVPACK=OFF


@build:
    cmake --build build

@run:
    build/tetris-sdl3

@format:
    find . \
        -regex '.*\.\(c\|h\)' \
        -not -path '*/build/*' \
        -exec clang-format -style=file --verbose -i {} \;

@test:
    ctest --test-dir build --output-junit xunit/results.xml

@clean:
    rm -rf build/
    rm -rf .cache/
