setup type="dev":
    cmake --preset=dev


@build:
    cmake --build build

@run:
    build/tetris-sdl3

@format:
    find . \
        -regex '.*\.\(c\|h\)' \
        -not -path '*/build/*' \
        -exec clang-format -style=file --verbose -i {} \;

@test:
    ctest --test-dir build --output-junit xunit/results.xml

@clean:
    rm -rf build/
    rm -rf build-release/
    rm -rf .cache/
