name: Update Submodules

on:
  schedule:
    - cron: "0 3 * * 0" # Runs every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Reset local changes
        run: |
          git reset --hard
          git clean -fdx

      - name: Update submodules
        run: |
          git submodule update --remote

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: automatically update submodules [bot]" || echo "Nothing to commit"
          git pull --rebase
          git push
